@url = https://ubiquitous-enigma-rqwjprp9qxw2p4x4-8080.app.github.dev

GET {{url}}/livros

###
POST {{url}}/livros
Content-Type: application/json

{
    "titulo": "Teste",
    "generos" : "Aventura",
    "autores" : "Eu mesmo"
}

###
DELETE {{url}}/livros/8